### PR TITLE
resolve #3

### LINKED ISSUE #3: Test presence and lack of targets
Test that there are no targets for test and live rows.  Test that there are targets of exactly 0 or 1 for validation and train.

10 NMR

### PR DESCRIPTION
**Pull request by pplonski**
Added tests for targets:

- no targets values in test and live data
- only 0 and 1 values in targets for train and validation data.

### CODE REVIEW

**Comment by kwgoodman** [comment]
The second test (0, 1) is [already in the repo](https://github.com/numerai/tournament-data-integrity/blob/master/integrity/check.py#L154). I caused the confusion by calling the targets 'labels'. (I also called data_type 'region').

So this PR really just becomes:
```
    idx = data.nonmissing_label_index()  # this line is already in check.py
    y = data.y[~idx]
    np.isnan(y).all()

**Comment by pplonski** [comment]
Thank you for looking into this. OK, so please add test for missing labels in test and live and my fix is not needed.

Maybe add comments in methods about what is tested in each.

**Comment by kwgoodman** [comment]
Each individual test has a code comment already I believe. 

I don't know how this works. I was wondering if I should just have made a competing PR. But you started, so why don't you take this one. Also one plea: try to keep the code flake8 clean.

**Comment by xanderdunn** [comment]
It sounds like this is not needed after #5.  Thanks for working on this @pplonski

**Pull request closed without merging**
